import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

import '../../model/doctor_model.dart';
import '../../model/user_model_supabase.dart';
import '../../supabase/supabase_controller.dart';
import '../../utils/common_appbar.dart';
import '../../utils/constants.dart';
import '../../utils/theme/app_colors.dart';
import '../../utils/theme/app_spacing.dart';

// TODO: This screen is generated by AI, not properly tested. Please review and test before using in production.
/// Doctor earnings / settlement overview (85% after working days).
class DoctorEarningsScreen extends StatefulWidget {
  const DoctorEarningsScreen({super.key});

  @override
  State<DoctorEarningsScreen> createState() => _DoctorEarningsScreenState();
}

class _DoctorEarningsScreenState extends State<DoctorEarningsScreen> {
  final _supabase = SupabaseController.to;
  bool _loading = true;
  Map<String, dynamic> _summary = {};
  DoctorModel? _doctor;
  String? _onboardingHint;

  @override
  void initState() {
    super.initState();
    _load();
  }

  Future<void> _load() async {
    setState(() => _loading = true);
    final user = await UserModelSupabase.getFromSecureStorage();
    final doctor = await _supabase.getDoctorByUserId(user?.id ?? 0);
    _doctor = doctor;
    if (doctor?.id != null) {
      _summary = await _supabase.getDoctorEarningsSummary(doctor!.id!);
    }
    _onboardingHint = _buildOnboardingHint(doctor);
    setState(() => _loading = false);
  }

  String? _buildOnboardingHint(DoctorModel? doctor) {
    if (doctor == null) {
      return 'Doctor profile not linked to your user account yet. Ask admin to set doctor.userId.';
    }
    final missing = <String>[];
    if ((doctor.drRegNumber ?? '').trim().isEmpty) {
      missing.add('registration number');
    }
    if ((doctor.razorpayAccountId ?? '').trim().isEmpty) {
      missing.add('Razorpay Route account');
    }
    if ((doctor.sessionTypeId ?? '0') == '0') {
      missing.add('session types');
    }
    if ((doctor.timeSlotId ?? '0') == '0') {
      missing.add('time slots');
    }
    if (missing.isEmpty) return null;
    return 'Complete onboarding: ${missing.join(', ')}.';
  }

  @override
  Widget build(BuildContext context) {
    final currency = NumberFormat.currency(locale: 'en_IN', symbol: '₹');
    return Scaffold(
      appBar: commonAppBar('Earnings'),
      body: _loading
          ? const Center(child: CircularProgressIndicator())
          : RefreshIndicator(
              onRefresh: _load,
              child: ListView(
                padding: const EdgeInsets.all(AppSpacing.md),
                children: [
                  if (_onboardingHint != null)
                    Container(
                      margin: const EdgeInsets.only(bottom: AppSpacing.md),
                      padding: const EdgeInsets.all(AppSpacing.md),
                      decoration: BoxDecoration(
                        color: AppColors.warningLight,
                        borderRadius:
                            BorderRadius.circular(AppSpacing.radiusMd),
                      ),
                      child: Text(
                        _onboardingHint!,
                        style: TextStyle(color: AppColors.warningDark),
                      ),
                    ),
                  Text(
                    _doctor?.name ?? 'Doctor',
                    style: Theme.of(context).textTheme.titleLarge,
                  ),
                  Text(
                    'You receive ~${_doctor?.percentageSplit?.toStringAsFixed(0)}% after settlement '
                    '(usually 2 working days). Platform fee ~${(100 - _doctor!.percentageSplit!).toStringAsFixed(0)}%.',
                    style: TextStyle(color: AppColors.textSecondary),
                  ),
                  const SizedBox(height: AppSpacing.lg),
                  Row(
                    children: [
                      Expanded(
                        child: _statCard(
                          'Today',
                          '${_summary['todayCount'] ?? 0}',
                          'sessions',
                          AppColors.medicalBlue,
                        ),
                      ),
                      const SizedBox(width: AppSpacing.sm),
                      Expanded(
                        child: _statCard(
                          'Pending',
                          '${_summary['pendingCount'] ?? 0}',
                          'to confirm',
                          AppColors.warning,
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: AppSpacing.sm),
                  Row(
                    children: [
                      Expanded(
                        child: _statCard(
                          'This week',
                          currency.format(_summary['weekEarnings'] ?? 0),
                          'your share',
                          AppColors.wellnessGreen,
                        ),
                      ),
                      const SizedBox(width: AppSpacing.sm),
                      Expanded(
                        child: _statCard(
                          'Settled',
                          '${_summary['settledCount'] ?? 0}',
                          'transfers',
                          AppColors.therapyPurple,
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: AppSpacing.lg),
                  _infoTile(
                    Icons.schedule,
                    'Slot management',
                    'Active slots are configured on your doctor profile '
                        '(timeSlotId). Contact admin to add or block slots.',
                  ),
                  _infoTile(
                    Icons.account_balance,
                    'Razorpay status',
                    (_doctor?.razorpayAccountStatus?.isNotEmpty == true)
                        ? _doctor!.razorpayAccountStatus!
                        : 'Not onboarded',
                  ),
                ],
              ),
            ),
    );
  }

  Widget _statCard(String title, String value, String subtitle, Color color) {
    return Container(
      padding: const EdgeInsets.all(AppSpacing.md),
      decoration: BoxDecoration(
        color: AppColors.surface,
        borderRadius: BorderRadius.circular(AppSpacing.radiusMd),
        border: Border.all(color: color.withOpacity(0.3)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(title, style: TextStyle(color: AppColors.textSecondary, fontSize: 12)),
          const SizedBox(height: 4),
          Text(
            value,
            style: TextStyle(
              fontSize: 20,
              fontWeight: FontWeight.w700,
              color: color,
            ),
          ),
          Text(subtitle, style: TextStyle(color: AppColors.textMuted, fontSize: 12)),
        ],
      ),
    );
  }

  Widget _infoTile(IconData icon, String title, String body) {
    return ListTile(
      contentPadding: EdgeInsets.zero,
      leading: Icon(icon, color: AppColors.medicalBlue),
      title: Text(title, style: TextStyle(fontWeight: FontWeight.w600)),
      subtitle: Text(body),
    );
  }
}
