// lib/ui/booking/booking_controller.dart
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:intl/intl.dart';
import 'package:physio_connect/model/doctor_model.dart';
import 'package:physio_connect/utils/enum.dart';
import 'package:razorpay_flutter/razorpay_flutter.dart';
import 'package:uuid/uuid.dart';

import '../../model/bookings_model.dart';
import '../../model/create_razorpay_order_model.dart';
import '../../model/session_type_model.dart';
import '../../model/time_slots_model.dart';
import '../../model/user_model_supabase.dart';
import '../../supabase/supabase_controller.dart';
import '../../utils/app_shared_preference.dart';
import '../../utils/constants.dart';

class BookingController extends GetxController {
  static BookingController get to => Get.find();

  BookingController();
  // Add a TextEditingController for address if not present in controller
  final TextEditingController addressController = TextEditingController();
  final TextEditingController houseNameBlockNumberController = TextEditingController();
  final RxString latitudeOfAddress = ''.obs;
  final RxString longitudeOfAddress = ''.obs;
  SupabaseController supabaseController =
      SupabaseController.to;

  final isLoading = false.obs;

  // Session Type
  final selectedSessionType = Rx<SessionTypeModel?>(null);
  final sessionTypes = <SessionTypeModel>[].obs;
  // Time slots data
  final selectedTimeSlot = Rx<TimeSlotModel?>(null);
  final bookingsModel = Rx<BookingsModel?>(null);
  final timeSlots = <TimeSlotModel>[].obs;

  final selectedDate = DateTime.now().obs;
  final razorpayPaymentId = ''.obs;
  var bookingId = 0;
  final createRazorPayOrderModel = Rx<CreateRazorPayOrderModel?>(null);

  UserModelSupabase? userModelSupabase;
  @override
  Future<void> onInit() async {
    super.onInit();
    isLoading.value = true;
    userModelSupabase = await UserModelSupabase.getFromSecureStorage();
    await getSessionTypesMaster();
    await getTimeSlotsMaster();
    isLoading.value = false;
  }

  // Load master data
  Future<void> getSessionTypesMaster() async {
    sessionTypes.clear();
    var response = await supabaseController.getSessionTypeMaster();
    sessionTypes.addAll(response);
  }

  // Load master data
  Future<void> getTimeSlotsMaster() async {
    timeSlots.clear();
    selectedTimeSlot.value = null;
    var response = await supabaseController.getTimeSlotsMaster(selectedDate.value);
    timeSlots.addAll(response);
  }

  void createAppointment(PaymentSuccessResponse paymentResponse, PaymentStatus paymentStatus) async {
    isLoading.value = true;
    var doctorModel = await DoctorModel.getFromSecureStorage();
    var doctorJson = jsonEncode(doctorModel?.toJson() ?? {});
    var timeslotJson = jsonEncode(selectedTimeSlot.value?.toJson() ?? {});
    var sessionTypeJson = jsonEncode(selectedSessionType.value?.toJson() ?? {});
    var patientJson = jsonEncode(userModelSupabase?.toJson() ?? {});
    // Via Notification Notify doctor about new booking
    await supabaseController.sentNotification(
      doctorModel?.userId ?? 1, "Yippee!!!, New Booking...",
      "New booking placed successfully.",);
    bookingsModel.value = BookingsModel(
      id: 0, // This will be auto-generated by the database
      userId: userModelSupabase?.id ?? 0,
      bookingStatus: BookingStatus.booked.name,
      timeSlotId: selectedTimeSlot.value?.id ?? 1, // Replace with actual time slot ID
      timeSlotJson: timeslotJson, // Replace with actual time slot ID
      doctorId: doctorModel?.userId ?? 1, // Replace with actual doctor ID
      doctorJson: doctorJson, // Replace with actual doctor ID
      sessionTypeId: selectedSessionType.value?.id ?? 1,
      price: selectedSessionType.value?.price ?? 1,
      sessionTypeJson: sessionTypeJson,
      patientJson: patientJson,
      paymentStatus: paymentStatus.name,
      paymentId: paymentResponse.paymentId!,
      orderId: paymentResponse.orderId,
      signature: paymentResponse.signature,
      doctorNotes: "No additional notes provided.",
      address: "${houseNameBlockNumberController.text}\n${addressController.text}",
      latLong: "${latitudeOfAddress.value}${LAT_LONG_SEPRATOR}${longitudeOfAddress.value}",
      bookingDate: DateFormat('yyyy-MM-dd').format(selectedDate.value),
      createdAt: DateTime.now().toString(),
    );
    await supabaseController.createNewBooking(bookingsModel.value!, doctorModel?.userId ?? 1);
    isLoading.value = false;

    // In a real app, this would create the appointment in your database
    final appointmentId = Uuid().v4();

    // Example implementation:
    // final appointment = booking_model.dart(
    //   appointmentId: appointmentId,
    //   userId: 'current-user-id', // Get from auth service
    //   therapistId: 'assigned-therapist-id',
    //   sessionTypeId: selectedSessionType.value!.sessionTypeId,
    //   date: DateFormat('yyyy-MM-dd').format(selectedDate.value),
    //   startTime: selectedTimeSlot.value,
    //   endTime: calculateEndTime(selectedTimeSlot.value, selectedSessionType.value!.durationMinutes),
    //   status: 'booked',
    //   createdAt: DateTime.now(),
    // );

    // Create payment record
    // final payment = PaymentModel(
    //   paymentId: Uuid().v4(),
    //   appointmentId: appointmentId,
    //   amount: selectedSessionType.value!.price,
    //   razorpayPaymentId: razorpayPaymentId.value,
    //   status: 'completed',
    //   timestamp: DateTime.now(),
    // );

    // Save to database
    // databaseService.saveAppointment(appointment);
    // databaseService.savePayment(payment);

    print('Appointment created with ID: $appointmentId');
  }

  Future<CreateRazorPayOrderModel?> createPendingBookingBeforePayment() async {
    isLoading.value = true;

    try {
      final doctorModel = await DoctorModel.getFromSecureStorage();
      final doctorJson = jsonEncode(doctorModel?.toJson() ?? {});
      final timeslotJson = jsonEncode(selectedTimeSlot.value?.toJson() ?? {});
      final sessionTypeJson = jsonEncode(selectedSessionType.value?.toJson() ?? {});
      final patientJson = jsonEncode(userModelSupabase?.toJson() ?? {});

      bookingsModel.value = BookingsModel(
        id: 0,
        userId: userModelSupabase?.id ?? 0,
        bookingStatus: BookingStatus.pending.name,
        timeSlotId: selectedTimeSlot.value?.id ?? 1,
        timeSlotJson: timeslotJson,
        doctorId: doctorModel?.userId ?? 1,
        doctorJson: doctorJson,
        sessionTypeId: selectedSessionType.value?.id ?? 1,
        price: selectedSessionType.value?.price ?? 1,
        sessionTypeJson: sessionTypeJson,
        patientJson: patientJson,
        paymentStatus: PaymentStatus.pending.name,
        paymentId: null,
        orderId: null,
        signature: null,
        doctorNotes: 'No additional notes provided.',
        address: "${houseNameBlockNumberController.text}\n${addressController.text}",
        latLong: "${latitudeOfAddress.value}${LAT_LONG_SEPRATOR}${longitudeOfAddress.value}",
        bookingDate: DateFormat('yyyy-MM-dd').format(selectedDate.value),
        createdAt: DateTime.now().toString(),
      );

      // create booking on server with pending status and get booking ID
      bookingId = await supabaseController.createNewBooking(bookingsModel.value!, doctorModel?.userId ?? 1);
      // Call the Supabase Edge Function to create Razorpay order
      var razorpayOrder = await supabaseController.callCreateRazorPayOrderSBEdgeFunction(bookingId, userModelSupabase?.id ?? 0,);
      createRazorPayOrderModel.value = razorpayOrder;
      return razorpayOrder;

      print('Pending booking created. Payment not captured yet.');
    } finally {
      isLoading.value = false;
    }
  }

  Future<void> updateBookingPaymentStatusAfterSuccess({
    required PaymentSuccessResponse paymentResponse,
  }) async {
    if (bookingsModel.value == null) {
      throw Exception('No pending booking exists to update.');
    }

    bookingsModel.value = BookingsModel(
      id: bookingsModel.value!.id,
      userId: bookingsModel.value!.userId,
      bookingStatus: BookingStatus.booked.name,
      timeSlotId: bookingsModel.value!.timeSlotId,
      timeSlotJson: bookingsModel.value!.timeSlotJson,
      doctorId: bookingsModel.value!.doctorId,
      doctorJson: bookingsModel.value!.doctorJson,
      sessionTypeId: bookingsModel.value!.sessionTypeId,
      price: bookingsModel.value!.price,
      sessionTypeJson: bookingsModel.value!.sessionTypeJson,
      patientJson: bookingsModel.value!.patientJson,
      paymentStatus: PaymentStatus.paid.name,
      paymentId: paymentResponse.paymentId,
      orderId: paymentResponse.orderId,
      signature: paymentResponse.signature,
      doctorNotes: bookingsModel.value!.doctorNotes,
      address: bookingsModel.value!.address,
      latLong: bookingsModel.value!.latLong,
      bookingDate: bookingsModel.value!.bookingDate,
      createdAt: bookingsModel.value!.createdAt,
    );

    await supabaseController.createNewBooking(bookingsModel.value!, bookingsModel.value!.doctorId);
  }

  Future<void> updateBookingPaymentStatusAfterFailure() async {
    if (bookingsModel.value == null) {
      return;
    }

    bookingsModel.value = BookingsModel(
      id: bookingsModel.value!.id,
      userId: bookingsModel.value!.userId,
      bookingStatus: BookingStatus.cancelled.name,
      timeSlotId: bookingsModel.value!.timeSlotId,
      timeSlotJson: bookingsModel.value!.timeSlotJson,
      doctorId: bookingsModel.value!.doctorId,
      doctorJson: bookingsModel.value!.doctorJson,
      sessionTypeId: bookingsModel.value!.sessionTypeId,
      price: bookingsModel.value!.price,
      sessionTypeJson: bookingsModel.value!.sessionTypeJson,
      patientJson: bookingsModel.value!.patientJson,
      paymentStatus: PaymentStatus.failed.name,
      paymentId: null,
      orderId: null,
      signature: null,
      doctorNotes: bookingsModel.value!.doctorNotes,
      address: bookingsModel.value!.address,
      latLong: bookingsModel.value!.latLong,
      bookingDate: bookingsModel.value!.bookingDate,
      createdAt: bookingsModel.value!.createdAt,
    );

    await supabaseController.createNewBooking(bookingsModel.value!, bookingsModel.value!.doctorId);
  }

  String calculateEndTime(String startTime, int durationMinutes) {
    final parts = startTime.split(':');
    final hour = int.parse(parts[0]);
    final minute = int.parse(parts[1]);

    final startDateTime = DateTime(2023, 1, 1, hour, minute);
    final endDateTime = startDateTime.add(Duration(minutes: durationMinutes));

    return '${endDateTime.hour.toString().padLeft(2, '0')}:${endDateTime.minute.toString().padLeft(2, '0')}';
  }
}